# Generated by Django 4.2.6 on 2023-11-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cover',
            field=models.ImageField(default=1, upload_to='cities/'),
            preserve_default=False,
        ),
    ]
